version: "2"

run:
  go: "1.22"

linters:
  default: standard
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused

issues:
  max-issues-per-linter: 10
  max-same-issues: 5
